# Generated by Django 4.2.1 on 2023-12-10 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Favourite_book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('summary', models.TextField(default=True)),
                ('author', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
                ('interesting', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='humster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True)),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Kvantorium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=10)),
                ('patronymic', models.CharField(blank=True, max_length=10)),
                ('Birthday', models.DateTimeField(max_length=15)),
                ('is_excellent', models.BooleanField(max_length=15)),
                ('is_not_excellent', models.BooleanField(max_length=15)),
            ],
        ),
    ]
