# Generated by Django 4.2.1 on 2024-01-28 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humster', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='humster',
            options={'ordering': ['-time_create']},
        ),
        migrations.AddField(
            model_name='favourite_book',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=255),
        ),
        migrations.AddIndex(
            model_name='humster',
            index=models.Index(fields=['-time_create'], name='humster_hum_time_cr_6d5c7f_idx'),
        ),
    ]
